### ISSUE TITLE
context buildah bug

### ISSUE THREAD

**Issue by dbgjerez** [tektoncd/catalog#1157]
https://github.com/tektoncd/catalog/blob/835896be3d306356f896c51d1b53fd1130ecfa6a/task/buildah/0.5/buildah.yaml#L80

The issue is simple to resolve. You can check the following images, where the first one runs satisfactorily, but the second one fails because the script's definition is inline. 

![image](https://user-images.githubusercontent.com/12196585/229834646-9ed16f7d-3818-4b2c-a2f1-97baee58b51c.png)

![image](https://user-images.githubusercontent.com/12196585/229835038-4f0d483a-1f12-41e2-a8da-f458d3d0f269.png)

Regards

**Comment by vdemeester** [comment]
@dbgjerez I am not sure I follow the issue. Is it because of the carriage return ? My guess is that the `quay.io/dborr…` comes from a result (from another `Task`) and that result has a *carriage return* in it. Ideally, the result should be written without that carriage return (so `echo -n …` or something).

**Comment by dbgjerez** [comment]
@vdemeester omg! you're right bro, I'm sorry.
@vdemeester++
Thanks a lot!
