### ISSUE TITLE
terraform task(s)

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/catalog#124]
We should provide Tasks that are able to use `terraform` to deploy things through it.

/kind feature

**Comment by raffamendes** [comment]
Would this task just execute terraform-cli commands? ( I never used terraforms, but if it's just to execute CLI commands, I'd be glad to create this task)

**Comment by vdemeester** [comment]
> Would this task just execute terraform-cli commands? ( I never used terraforms, but if it's just to execute CLI commands, I'd be glad to create this task)

I would think so yeah :angel:

**Comment by raffamendes** [comment]
This is actually going to be 2 tasks, because the way terraforms authenticate, each provider need a different set of enviroment variables, this is easy to achieve with ```envFrom``` but this would only work in kube1.6+ clusters, still trying to figure a way to dynamically set environment variables for older version of kube that is not a ugly workaround :sweat_smile:

**Comment by tjhiggins** [comment]
Def interested in this feature. Would love to play around when you have the envFrom working!

**Comment by raffamendes** [comment]
/close 
this issue was resolved with the PR #149 
cc @tjhiggins
