### ISSUE TITLE
Project recommendation: best practices for writing new tasks?

### ISSUE THREAD

**Issue by ad22** [tektoncd/catalog#281]
Looking for maintainer guidance on the following options for writing new tasks:

1. Use shell via already available images when possible? Should there be a limit to this approach?
PS: Personally not a fan of this approach, It can get fairly unwieldy to maintain, very quickly. Another con, `ash` used by the alpine image is not as fully featured as bash.

2. Publish docker images w/ pre-built binary. A place to store and publish these docker images would be a pre-req, along with capability to iterate (ko?). Based on the comment in #29, this might not be viable.

3. Hybrid? Use go/python code embedded into the task via shell. Python is likely easier, but here's an incomplete example for go that "compiles". Con, IDE's can't understand it fully (w/ the shell substitution for params).
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: code-in-shell
  namespace: tekton-pipelines
spec:
  workspaces:
  - name: workspace
    mountPath: /workspace
  params:
  - name: subdirectory
    description: subdirectory
    type: string
    default: "src"
  steps:
  - name: build-git-init
    image: golang:alpine
    script: |
      cat <<'EOF' >> git-init.go
      package main

      import (
      	"fmt"
        "bytes"
      	"os"
      	"os/exec"
      )

      func run(dir string, args ...string) (string, error) {
      	c := exec.Command("git", args...)
      	var output bytes.Buffer
      	c.Stderr = &output
      	c.Stdout = &output
      	if dir != "" {
      		c.Dir = dir
      	}
      	if err := c.Run(); err != nil {
      		fmt.Printf("Error running git %v: %v\n%v", args, err, output.String())
      		return "", err
      	}
      	return output.String(), nil
      }

      func mainWithExit() int {
        outputPath := "$(workspaces.workspace.path)/$(params.subdirectory)"
      	_, err := run(outputPath, "init")

       if err != nil {
          return 1
        }
        return 0
      }

      func main() {
          os.Exit(mainWithExit())
      }
      EOF
 
      cat git-init.go 
      mkdir -p /usr/local/go/src/git-init && mv git-init.go /usr/local/go/src/git-init && cd /usr/local/go/src/git-init && go build -v
      ls -ltr /usr/local/go/src/git-init/*
      ls -ltr /usr/local/go/bin/*
      mv /usr/local/go/src/git-init/git-init $(workspaces.workspace.path)
  - name: run-git-init
    image: alpine/git:latest
    command: ["sh"]
    args: ["-c", "$(workspaces.workspace.path)/git-init"]
```

**Comment by ImJasonH** [comment]
Thanks for bringing this up!

> PS: Personally not a fan of this approach, It can get fairly unwieldy to maintain, very quickly.

I think this is the main point against using `script:` heavily. If you're writing more than a handful of lines of Bash (or Python, or Go, or anything), you probably want to be able to test it, or at least run it in isolation outside of Tekton, and inlining everything in a `script:` makes that impossible.

`script:` is ideal for short one-liners, often using core tools like `grep` and `sed`, or standard tools like `git` and `curl` or otherwise purpose-built (and independently tested) CLI tools like `gcloud`. In any of these cases, you're (_briefly_) using a simple standard CLI tool which presumably has undergone thorough testing. Params can be passed to the tool simply via command-line flags.

Writing hundreds of lines of Python inside YAML sounds like a surefire way to accidentally summon some kind of unholy daemon. 😈 

So if the recommendation is to move your logic into a binary in an image, we need to document best practices for doing that, which could be `ko` for simple Go CLIs, or just standard `.py` or `.sh` files in an image. There are already plenty of tutorials and best practices for building container images, so we should probably just link to one of those.

**Comment by bobcatfish** [comment]
I'm gonna dump some things in here as I notice them.

In https://github.com/tektoncd/catalog/pull/287 I noticed that we should recommend using workspaces (and eventually credentials! 😉  @sbwsg ) instead of volumes + volumemounts

**Comment by ad22** [comment]
Thanks @ImJasonH, that answers my main question/concern and #2 seems the best path forward with the downside that there is no centralized location for images (which I hope is reconsidered).

>script: is ideal for short one-liners, often using core tools like grep and sed, or standard tools like git and curl or otherwise purpose-built (and independently tested) CLI tools like gcloud. In any of these cases, you're (briefly) using a simple standard CLI tool which presumably has undergone thorough testing. Params can be passed to the tool simply via command-line flags.
This line would be nice to have in recommendations.md (#288).

Feel free to use this issue for other items or close it.
