### ISSUE TITLE
Add task for sending CloudEvents

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/catalog#331]
# Expected Behavior

That there is a task for sending CloudEvents.

Typical use-cases: 

- Notifying that a deployment occured.
- Notifying that a `TaskRun` failed e.g. failed unit-test.
- Notifying result from a Canary Analyze

This task would be on pair with the existing Slack an Telegram-tasks, but for CloudEvents.

# Actual Behavior

I don't see this exists in Catalog

**Comment by bobcatfish** [comment]
Some context, one of the reasons this wasn't done already is that some of the CloudEvents logic in the CloudEvent PipelineResource happens in the controller vs. in the step containers like all the other PipelineResources. And one of the reasons for THAT was b/c in order to know if the currently executing Task has succeeded or failed, you had to wait until the entire thing completed (and failure would stop execution of any subsequent containers).

+ @afrittoli if he wants to add any more context

**Comment by jlpettersson** [comment]
>some of the CloudEvents logic in the CloudEvent PipelineResource happens in the controller vs. in the step containers like all the other PipelineResources. And one of the reasons for THAT was b/c in order to know if the currently executing Task has succeeded or failed, you had to wait until the entire thing completed (and failure would stop execution of any subsequent containers).

Right, I understand. Sounds like a mix of intern/technical events e.g. Kubernetes `Event` and "result reporting". Ah, right, it makes sense that a reporting-task will not execute if previous task failed, so such tasks must be places in `finally:`.

My intention here var purely business-oriented, e.g. letting the user know the result of a Canary-Analysis. In such case, I think this would provide value, but I agree that it would be hard to use for reporting errors. It can also be used for initiating things remote, or communicating with cloud services.
