### ISSUE TITLE
Issue with golang-build

### ISSUE THREAD

**Issue by jlpettersson** [tektoncd/catalog#461]
# Expected Behavior

That I can use `golang-build` task without modifications

# Actual Behavior

I got this error when building a simple go app:

```
can't load package: invalid import path "$(params.package)/cmd/<myapp>"
```

# Steps to Reproduce the Problem

1. use the golang-build task to build

# Additional Info

I use Go modules - I think that should be the defaul behaviour in august 2020 :)

----

The solution I used to get the task working was by removoing this line:

```
    mountPath: /workspace/src/$(params.package)
```

**Comment by vdemeester** [comment]
@jlpettersson so the error seems to say that `params.package` wasn't provided ? As it doesn't have a default value it is required.
My guess is that you are using go modules and you want to build `.` (aka what is mounted in `/workspace/src`), am I right ?

**Comment by jlpettersson** [comment]
yes, that seems to be correct

**Comment by sbwsg** [comment]
I believe the issue here is that variable expansion isn't supported in `workspaces.mountPath`.  So it's always `/workspace/src/$(params.package)`.  Looks like this is a problem in all of the golang tasks.

See feature request to add support for variable expansion in `workspaces.mountPath` here: https://github.com/tektoncd/pipeline/issues/3152
