### ISSUE TITLE
RFE: update all catalog Tasks/CatalogTasks to make the image field a parameter

### ISSUE THREAD

**Issue by itewk** [tektoncd/catalog#562]
# Expected Behavior
ability to at use/runtime change the image being used in a task.

## Reasons

1. in disconnected environments can not access the hard coded image
2. in enviroments where a image mirror such as quay/nexus/artifactory is used need ability to pull the images from that internal mirror
3. need image with non root known UID to deal with git nonesense and work in environments where giving privilaged isn't permited

# Actual Behavior

`image` field is hard coded

# Additional Info

Can certainly clone these catalog tasks down and edit them with a different image or the parameter before installing in a given environment, but it would be nice if didn't have to modify the upstream and could just install as is.

**Comment by chmouel** [comment]
This sound a reasonable request to make it as policy

**Comment by itewk** [comment]
@ImJasonH open another TEP for this?

**Comment by chmouel** [comment]
that's for tektoncd/catalog, we haven't used a TEP before (but we could :)), we would need someone who can own al these changes across all tasks.

**Comment by itewk** [comment]
@ImJasonH @chmouel can we bring this back to life?

/remove-lifecycle rotten this is still a valid and needed request

**Comment by ImJasonH** [comment]
Hey Ian 👋 

While we can update and try to document/enforce that all Tasks in the Catalog support image as a param, we probably won't be able to extend that same control over the Hub, where users can contribute their own Tasks without code review. Longer-term, the Hub is the place where Tasks will probably be shared and pulled from.

I also think there'll be a bit of difficulty enforcing this policy in general, since Tasks can have multiple steps, and can change over time, so supporting params like "first-step-image" and "second-step-image" can break assumptions when a third step gets added between them (or removed, or its semantics change, etc.). In general, Tasks should be mostly black-boxes to users, at least ideally.

The motivating cases you describe are indeed motivating though. I've seen a solution in other contexts where airgapped clusters or operators using a proxy/mirror registry put a [mutating webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/) in place that automatically changes any images requested by any Pod (incl Tekton TaskRun Pods) to pull from the mirror registry instead. This also lets the webhook and registry enforce image policies, etc. That might be a more flexible solution for you in general, rather than requiring/asking Tasks to make the image parameterizeable.

In the meantime, feel free to send PRs for any Tasks you want to use that aren't parameterizeable, and we can get those in at least.

**Comment by itewk** [comment]
@ImJasonH good point about the mutating webhook. Will look to do individual PRs for individual (Cluster)Tasks.

I'll close this.
