### ISSUE TITLE
Policy for when to bump versions of Tasks that depend on images in tektoncd/pipeline?

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/catalog#644]
# Expected Behavior

Whenever there is a change to a Task, we should bump the version. ([TEP-0003](https://github.com/tektoncd/community/blob/main/teps/0003-tekton-catalog-organization.md#versioning-resources)).

We should decide if we want to follow this strategy for Catalog items that depend on images published in tektoncd/pipeline ([these images](https://github.com/tektoncd/pipeline/tree/master/cmd))and be consistent about it. 

# Actual Behavior

We sometimes bump the version of the image being used b/c we've made an update but we rarely bump the version of the Task itself. (e.g. https://github.com/tektoncd/catalog/pull/597)

# Steps to Reproduce the Problem

Example:

# Additional Info

More discussion in https://github.com/tektoncd/pipeline/pull/3258

**Comment by vdemeester** [comment]
> Whenever there is a change to a Task, we should bump the version. ([TEP-0003](https://github.com/tektoncd/community/blob/main/teps/0003-tekton-catalog-organization.md#versioning-resources)).

So, in the TEP, the rules around "images" are

> New image(s) is(/are) used for the Task
> - For **images that we own** we should **only bump the version if the new version breaks CI** or if **release notes include changes on the Tekton image**
> - For images that we do not own: it should be the responsibility of the author of the task to verify if changing an image version requires a new Task version
> - When the image for a step is specified via an input params, we should treat changes to the default value of that param in the same way as changes to a step image

I did put emphasis on part I feel are important 😛. `tektoncd/pipeline` are images we own, so, the rules there is "if it breaks the CI or if we know (we == tektoncd/pipeline maintainers) something changed in the image". This means, we don't necessarily need to bump the task version *but* it's on us (it's our responsability.. if we break users).

/cc @tektoncd/core-maintainers @tektoncd/catalog-maintainers

**Comment by chmouel** [comment]
Does  the binaries from tektoncd/pipeline ensure compatibility between version of pipelines?

**Comment by sbwsg** [comment]
> Does the binaries from tektoncd/pipeline ensure compatibility between version of pipelines?

Taking `git-init` as an example, the only intentional breaking change we've introduced (that I can remember) is that we dropped support for short git hashes [when we added the `refspec` field](https://github.com/tektoncd/pipeline/pull/2320).

Because we use `git-init` in PipelineResources I think we would hear user reports pretty quickly if a new version of Pipelines broke that image.  But I don't think we __ensure__ compatibility in the same strict way we do with Tekton's API surface for example.  Just that the primary changes we've introduced to the image are additive rather than changing or taking away from how it works.
