### ISSUE TITLE
Align tasks in the catalog to the authoring reccomendations

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/catalog#710]
# Expected Behavior

All tasks in the catalog are aligned to the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md).

# Actual Behavior

Most tasks are not.

# How to Address this Issue

- This does not have to be solved in one go, it could be broken down into many small tasks - feel free to open other, more specific, issues - and link them here
- A big plus would be being able to enforce as many recommendations as possible programmatically, to avoid regressions in future
- If the changes to the task change the task interface / container image, a new version will be required

**Comment by afrittoli** [comment]
@mogsie @bittrance @sbwsg @vdemeester FYI

**Comment by afrittoli** [comment]
We might want to verify shell scripts with [shellcheck](https://www.shellcheck.net/) too.

**Comment by chmouel** [comment]
> We might want to lint shell scripts with shellcheck too.

`catlin lint script` command should be able to help with that : 

https://github.com/tektoncd/plumbing/commit/e6e08917cd14d17ef4be8f05d2dfd89a0206c04d#diff-273ca055ed4a979a860dee854cabd071f961c77ab531140dab24dda4868d7eec

**Comment by bittrance** [comment]
Regarding param expansion in `script`. I took a quick scan with `grep -lr script: task/ | grep -v tests/ | while read f ; do echo $f ; echo ; yq eval '.spec.steps[].script' $f ; echo '-------------------------------------' ; done`. Many tasks can probably be fixed with limited effort, but the [kubernetes-actions](https://github.com/tektoncd/catalog/blob/85435f9aa4eb10a7ae7d48d96ad57b39e2bcf394/task/kubernetes-actions/0.2/kubernetes-actions.yaml#L49) one is problematic, because it effectively treats multi-line expansion as a feature. I assume it is an important member of the catalog, so a task with different semantics is probably needed.
