### ISSUE TITLE
Add Tasks to cover PipelineResource use cases

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/catalog#95]
In the recent [PipelineResource working group](https://docs.google.com/document/d/1p6HJt-QMvqegykkob9qlb7aWu-FMX7ogy7UPh9ICzaE/edit#heading=h.qlw6qthulviy) and as presented during [Oct. 2 working group](https://docs.google.com/document/d/1rPR7m1Oj0ip3bpd_bcS1sjZyPgGi_g9asF5YrExeESc/edit#heading=h.cmh0v8dadexs), and related to tektoncd/pipeline#1369 :

In the most recent PipelineResource working group we landed on the idea of keeping PipelineResources as Alpha when the rest of the Tekton resources move to Beta. So with that approach we'll need to make sure that our docs correctly reflect the "right" way to work with external resources.

In this direction, we need to provide generic tasks that cover the use case of PipelineResource today, e.g. a GitTask, a DockerImageTask, etc... This issue is there to track work related to that.

Current PipelineResource to cover
- [x] `GitResource` #123 
- [ ] `ClusterResource`
- [x] `PullRequestResource`
- [x] `GCSResource`
- [ ] `S3resource`

Additionnal generic tasks
- [ ] Other VCS, like `mercurial`, …

Feel free to add your ideas/need in comment, I'll update this issue's description :wink:

**Comment by sbwsg** [comment]
Another part of this that we'll need to think about is that currently the PipelineResources have their credentials initialized using Pipeline's [creds-init image](https://github.com/tektoncd/pipeline/tree/master/cmd/creds-init).

@bobcatfish and I were talking about this a bit last week / a few weeks ago.  Maybe we could offer up creds-init as its own Task to ease migration off of PipelineResources?  The only problem them would be that the user would need to provide a workspace so that the initialized creds can be written to it and then mounted at the appropriate place by the PipelineResource tasks themselves.  Seems complicated to me.  This is, I think, where having tasks with [Pre and Post Run Steps](https://github.com/tektoncd/pipeline/issues/1838) could really help out - a creds-init PreRunStep could initialize a Task's `~/.ssh` / `~/.docker` directories based on attached secrets.

**Comment by stobias123** [comment]
@sbwsg - Any chance you could point a weary traveler to docs about this creds implementation? I'm having trouble finding how to set creds for the [git-clone](https://hub-preview.tekton.dev/detail/34) task in catalog.

**Comment by vinamra28** [comment]
hi @stobias123, [Using SSH authentication in git type Tasks](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#using-ssh-authentication-in-git-type-tasks).

**Comment by stobias123** [comment]
Oof missed the note in the docs. Thanks.
